### ISSUE TITLE
Undefined reference to typeArrayOopDesc::long_at_put

### ISSUE THREAD

**Issue by galderz** [graalvm/labs-openjdk-11#5]
`jvmci-20.2-b01` tag fails to build with JDK 11.0.7 as boot and the following command:

```
$ python build_labsjdk.py
```

Error:

```
Linking libjvm.so
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/build/linux-amd64/hotspot/variant-server/libjvm/objs/jvmciRuntime.o: In function `JVMCIRuntime::init_JavaVM_info(_jlongArray*, JVMCIEnv*)':
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:784: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:785: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:786: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:787: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
collect2: error: ld returned 1 exit status
gmake[3]: *** [/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/build/linux-amd64/support/modules_libs/java.base/server/libjvm.so] Error 1
gmake[3]: *** Waiting for unfinished jobs....
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/build/linux-amd64/hotspot/variant-server/libjvm/objs/jvmciRuntime.o: In function `JVMCIRuntime::init_JavaVM_info(_jlongArray*, JVMCIEnv*)':
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:784: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:785: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:786: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/./src/hotspot/share/jvmci/jvmciRuntime.cpp:787: undefined reference to `typeArrayOopDesc::long_at_put(int, long)'
collect2: error: ld returned 1 exit status
gmake[3]: *** [/home/g/workspace/qollider/0206/graalvm/labs-openjdk-11/build/linux-amd64/hotspot/variant-server/libjvm/gtest/libjvm.so] Error 1
gmake[2]: *** [hotspot-server-libs] Error 1

ERROR: Build failed for targets 'product-bundles static-libs-bundles' in configuration 'linux-amd64' (exit code 2)
```

**Comment by dougxc** [comment]
I've updated the tag to point to the commit that fixes this issue. Note that a `jvmci-*` tag is only "fixed" once a JVMCI release is actually made (at which point binaries will be uploaded against the tag).
